### ISSUE TITLE
localhost:XXXX - is not working again when I want it

### ISSUE THREAD

**Issue by PBemm69** [coleam00/bolt.new-any-llm#147]
### Describe the bug

This is just a clarification.  First time when I run pnpm run dev I got the localhost url.

However, the moment I delete the command prompt, localhost:XXXX does not work. Is this an issue with my laptop?  

When I installed the LAMP server to run wordpress locally, next time when I use that localhost it works.  In Bolt.new am I doing something wrong.

Pls assist.

### Link to the Bolt URL that caused the error

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by hillct** [comment]
More detail is needed here in order to formulate a meaningful response:

What OS and version?
What is meant by "However, the moment I delete the command prompt, localhost:XXXX does not work."
Do you mean that you're launching Bolt.nw in h foregroud and want it in the background? Does delting he prompt mean exiting the running application? (Ctrl-C)

Are you expecting an Ollama connection, or are you referring to the main bolt.new web interface?

M guess, having read your post several times is that you mean to say that you're closing h command prompt window where the bolt.new application is running, and expecting it not to close. I think you'll find Docker to be the best solution in this case because, while you can run node in the background, process management can get messy (on windows at least) and it sounds like you're looking for a more turnkey solution.

**Comment by PBemm69** [comment]
Actually, my laptop's OS system is Windows10Pro.  Actually, my technical knowledge is very low. I will need to search for it as to how I can do it.  Thanks.

**Comment by hillct** [comment]
Without getting into the weeds, the non-technical answer is you should not expect to be able to close a windows, command line window and have processes launched in that window, in the foreground, meaning the system prompt does not return automatically after you've run a command. This is generally intentional and reasonable. In this way, you can view error messages as they arise, and generally have greater control for debugging purposes. As a non-technical person you may not find this useful so in that case, consider minimizing the window rather than closing the command line process and related child processes.

Beyond that I recommend you read up on Windows process management. This general knowledge will serve you well in your computing odyssey.

**Comment by PBemm69** [comment]
Thanks for the reply.

Let me recap. If you want to work with Bolt, which Localhost:XXXX, then keep open the Command Prompt.  Once you close it, the local host will stop working. Command prompt is keeps the server type thing going what is need in the back end what is needed to work on the local host.

Then each time you need to start, Bolt, you need to run "pnpm run dev" on the command prompt.
