### ISSUE TITLE
Not working after following eaxt setup process

### ISSUE THREAD

**Issue by veerababumanyam** [coleam00/bolt.new-any-llm#167]
### Describe the bug

I followed the document and video as well, installed in docker and configured the .env file as well. However, I am getting errors. PFA pf the pictures for your reference 
![a11](https://github.com/user-attachments/assets/56353424-60d5-4994-9d5b-681a15bb4e26)
![a12](https://github.com/user-attachments/assets/c919eb34-7db0-45ca-ba06-47f7ce665754)

### Link to the Bolt URL that caused the error

https://github.com/coleam00/bolt.new-any-llm

### Steps to reproduce

Authorization failed

### Expected behavior

Work normal

### Platform

- OS: Windows
- Browser:  Chrome
- Version: [e.g. 91.1]

**Comment by lossehelin** [comment]
only openrouter works for me. nothing else works and i get that message

**Comment by edqu** [comment]
I am having the same problem

**Comment by Psxmaster83** [comment]
yeah code is broken ... i added all the apis but that  fix nothing

**Comment by thorvak** [comment]
Same issue with mistral

**Comment by TommyHolmberg** [comment]
Same. It looks like it's trying to connect to OpenAI base api url, `https://api.openai.com/v1/chat/completions` and `https://platform.openai.com/account/api-keys` regardless of which model you chose. On my setup it's supposed to connect to localhost (litellm) but it's still using regular OpenAI base url.

**Comment by hellomikko** [comment]
All these so called Forkers, not one in 2 hours since the last post said a word. A community project it was said, this project has has more errors than Microsoft itself and theres rarely any support. In almost all these threads Ive seen nothing but people talking junk too each other when 1 person asks for some support. Do yourselves a favor, get off this repo if you are not really here to help but for clout just to fork something/say something and not helping.

I literally came here because even as an experienced coder too at least know how to follow instructions to get me started, still experienced alot of their pain trying to get it setup to getting the API keys to work.

So please stop with the nonsense and lets help each other. Yall act like this is reddit.

Also, as a Pro member on most AI's, the only basic that really works is Gemini and GPT40. Thats it and both of these do not know anything about coding beyond the word basic.

I think most people are here because of Bolt and V0. Not any other BS. So lets git it folks.

**Comment by hellomikko** [comment]
> [veerababumanyam](/veerababumanyam)

Both API's are a coding issue, just to let you know. You can reproduce keys 100x and still the results are the same. I know because Ive installed this thing 100 times and remade my keys 1000x.

**Comment by coleam00** [comment]
I'm sorry you guys are running into this issue! Could you try installing outside of Docker and see if the issue persists? The docker setup is newer so there could be some issues with it. That is something I am looking into this week!

**Comment by TommyHolmberg** [comment]
@coleam00 I think I have found the culprit to my problem and I don't think it's related to this issue.

I'm trying to use Githubs api for gpt-4o, so I have github/gpt-4o as model and their azure url as api base url.

In `stream-text.ts` the function `streamText` tries to figure out the provider by comparing model names. Since it only uses the model name, the first provider that it lands on is OpenAI. You'll see the same problem for most models provided in Githubs API. Or in Ollama if it uses the same model name as any other provider.

The correct way to solve the issue is to use the provider selected in UI. At the moment it doesnt seem to be included in the parameters that are sent to the streamText function.

**Comment by TommyHolmberg** [comment]
After further investigation and code changes I get the url to be correct. But even now, I seem to face the same issue. It says connection refused. In litellm I can se that the `GET /models` call does get through. But I can't see any calls to `chat/completions` . That indicates that the connection from _streamText() never happens. That function seems to be in the `ai` package. Perhaps the issue is in that package.

**Comment by hellomikko** [comment]
> I'm sorry you guys are running into this issue! Could you try installing outside of Docker and see if the issue persists? The docker setup is newer so there could be some issues with it. That is something I am looking into this week!
> 
> @veerababumanyam @lossehelin @thorvak @Psxmaster83 @TommyHolmberg @hellomikko

Ok I got it to work last night, sorry I was goin at it once I got it installed the normal way and can confirm it does work with exception to a major issue with API keys that are not working. However Gemini and GPT40 were the only two I could get to work, Anthropic isnt playing nicely which is my favorite by far, but... ahh well.

Steps I did to make it work:
- As it stated, its by far easier and better to install and run this with `pnpm`. If you dont have it installed: [try getting it here and install it first before anything else.](https://pnpm.io/)
- Clone the repo as stated on the ReadMe.md.
- Once its cloned, git into or CD the physical folder and open it with your Command Prompt. Yup, you heard me, Command Prompt that sucka. It works for me with Command Prompt Admin.
- While its installing the dependencies, open your .env file and add your API keys. @coleam00 was nice enough to even provide the links directly too, so you dont have to search under the cookie crumbs.
- Once its dont with installing the dependencies and youve already edited the `.env` file with your API Key(s), open your favorite IDE, mine is Fleet or vsCodium depending on how I feel. Than in your IDE open the command panel and type `pnpm install`.
- You should than be ok after that point for when its done installing, run `pnpm run dev`.

These instructions were just more simplified for anyone who likes to read less.


While I am not a Docker person, I will wait and see with others say about the Docker version and also await @coleam00 with some fixes with the API keys.

**Comment by coleam00** [comment]
@hellomikko Thank you for following up here and giving some nice and simple instructions!

Could you clarify the issue you are running into with some of the APIs? I tested and they are all working for me.

**Comment by coleam00** [comment]
@TommyHolmberg  I pushed a fix that will probably help you with the latest issue you are describing! Getting the container to communicate with Ollama outside of the container. Give it a shot!

**Comment by sahni1977** [comment]
@coleam00  This is not working. I have taken latest from repo and build it. I am using only ollama APIKEY default URL. It gives me 401 error. Ollama is runningon my local and application too.

I don't think Ollama require any authentication in local. It seems its going default to anthropic only.

2024-11-06 12:31:49   cause: undefined,
2024-11-06 12:31:49   url: 'https://api.anthropic.com/v1/messages',
2024-11-06 12:31:49   requestBodyValues: {
2024-11-06 12:31:49     model: 'claude-3-5-sonnet-20240620',
2024-11-06 12:31:49     top_k: undefined,
2024-11-06 12:31:49     max_tokens: 8000,
2024-11-06 12:31:49     temperature: 0,
2024-11-06 12:31:49     top_p: undefined,
2024-11-06 12:31:49     stop_sequences: undefined,
2024-11-06 12:31:49     system: '\n' +
2024-11-06 12:31:49       '    13. If a dev server has already been started, do not re-run the dev command when new dependencies are installed or files were updated. Assu'... 5141 more characters,
2024-11-06 12:31:49     messages: [ [Object] ],
2024-11-06 12:31:49     tools: undefined,
2024-11-06 12:31:49     tool_choice: undefined,
2024-11-06 12:31:49     stream: true
2024-11-06 12:31:49   },
2024-11-06 12:31:49   statusCode: 401,
2024-11-06 12:31:49   responseHeaders: {
2024-11-06 12:31:49     'cf-cache-status': 'DYNAMIC',
2024-11-06 12:31:49     'cf-ray': '8de336ef89df3adf-BOM',
2024-11-06 12:31:49     connection: 'keep-alive',
2024-11-06 12:31:49     'content-length': '97',
2024-11-06 12:31:49     'content-type': 'application/json',
2024-11-06 12:31:49     date: 'Wed, 06 Nov 2024 07:01:50 GMT',
2024-11-06 12:31:49     'request-id': 'req_01SQ4upFxtgwu796HLqV5uXU',
2024-11-06 12:31:49     server: 'cloudflare',
2024-11-06 12:31:49     via: '1.1 google',
2024-11-06 12:31:49     'x-robots-tag': 'none',
2024-11-06 12:31:49     'x-should-retry': 'false'
2024-11-06 12:31:49   },
2024-11-06 12:31:49   responseBody: '{"type":"error","error":{"type":"authentication_error","message":"x-api-key header is required"}}',
2024-11-06 12:31:49   isRetryable: false,
2024-11-06 12:31:49   data: {
2024-11-06 12:31:49     type: 'error',
2024-11-06 12:31:49     error: {
2024-11-06 12:31:49       type: 'authentication_error',
2024-11-06 12:31:49       message: 'x-api-key header is required'
2024-11-06 12:31:49     }
2024-11-06 12:31:49   },
2024-11-06 12:31:49   [Symbol(vercel.ai.error)]: true,
2024-11-06 12:31:49   [Symbol(vercel.ai.error.AI_APICallError)]: true

**Comment by veerababumanyam** [comment]
Installed on windows directly and it is working perfect 
![image](https://github.com/user-attachments/assets/9cf9d123-0f55-4521-9c4d-f71c722db692)
