### ISSUE TITLE
After reopening an old project and engaging in multiple rounds of conversation, subsequent code modifications are lost the next time the project is opened.

### ISSUE THREAD

**Issue by Corwin006** [coleam00/bolt.new-any-llm#235]
### Describe the bug

First thanks the great job!
Recently, I tried to create a project. After several attempts, I often found that previously resolved design issues reappeared. Upon careful inspection, I discovered that the code was missing. It has been confirmed that this is not due to the code being overwritten during the AI generation process. Projects with resolved issues are incorrect the next time they are opened.

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/project-name

### Steps to reproduce

1. Open an old project: select and open a previously created project from the project list.
2. Engage in multiple rounds of conversation: Within the project, engage in multiple rounds of conversation, during which I may make several code modifications and updates.
3. Save and close the project: After completing the conversation and code modifications, I close the browser.
4. Reopen the project: The next time I open the same project, I find that the previous code modifications have not been saved, or some modifications are missing.

### Expected behavior

Hope when the next time the project is opened, the code shoud fully retain the final modifications from the last session.

### Platform

- OS: [Windows]
- Browser: [Chrome,]
- Using anthropic/claude-3-5-haiku-20241022

**Comment by thecodacus** [comment]
this is an annoying problem, its making me run a fresh project on each test

**Comment by frogman544** [comment]
> this is an annoying problem, its making me run a fresh project on each test

Same for me, this should be a HIGH PRIORITY since persisting the codebase between conversations saves lots of tokens.
This might not be an issue if you have lots of time and money :)

**Comment by thecodacus** [comment]
actually it doesn't require token to restore the project as all the messages are cached in browser its just running the existing messages and re creating the project from cache. 

but the issue here is its not able to recreate as its not processing the messages in sequence but in parallel which is causing the issue.. 

if the actions doesn't get executed in the same order as it happened originally, the recreated project gets corrupted

**Comment by frogman544** [comment]
> actually it doesn't require token to restore the project as all the messages are cached in browser its just running the existing messages and re creating the project from cache. 
> 
Technically it doesn't require tokens to restore the project (because of cache) but in practice, an older version of the project is loaded and you need additional tokens to get to the same functionality that you left when closing the browser (that you have in cache but is not loaded).
>
> but the issue here is its not able to recreate as its not processing the messages in sequence but in parallel which is causing the issue.. 
> 
Is there a way to not load all the messages? This issue is not present in the bolt.new project, so there must be a fix for this.
>
> if the actions doesn't get executed in the same order as it happened originally, the recreated project gets corrupted

**Comment by thecodacus** [comment]
the bolt actually saved the code to the cloud periodically or maybe after each AI response.. and when you open that chat again it loads from the cloud
