### ISSUE TITLE
Cant get env vars to stick?

### ISSUE THREAD

**Issue by sengland-4way** [coleam00/bolt.new-any-llm#298]
### Describe the bug

Im sure its not a bug, but I dont understand why I cant get the environment variables to work.

1. I cloned the repo
2. I mv .env.example .env.local
3. edited it and populated the OLLAMA_API_BASE_URL=http://localhost:11434
4. run the docker build npm commands
5. started the container using docker compose
6. WARN[0000] The "OLLAMA_API_BASE_URL" variable is not set. Defaulting to a blank string.

tried a few times with same result

1. reverted to running it locally (not in docker)
2. pnpm run dev --host=0.0.0.0
3. load page in canary
4. ollama list is empty 
5. receive the following debug messages:

undefined
undefined
undefined

I imagine because the ollama API base is still empty....

### Link to the Bolt URL that caused the error

Base URL

### Steps to reproduce

As above

### Expected behavior

Ollama model list to appear

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by smarthiesbs** [comment]
I think the definition of the two operating states `development` and `production` is not particularly well documented so far, so that without the necessary experience you can quickly get confused with the docker-compose and the handling of the env variables. maybe a potential for misconfigurations...

Personally, I have decided to only build the development container and have removed all the production stuff from the compose file: Because of the bind-mount of the entire project directory to `/app`, ottodev then only seems to access `.env.local` for it's runtime configuration (but can be overriden by .env?!).  For me it's best for bugfixing :)

Changes to that file are also tracked live, so if I change the API keys or the base URL of Ollama or LMStudio (OpenAI-like) in that .env.local, you can see in the container logs that it applies the change immediately:

```
2024-11-16 00:29:51 11:29:51 PM [vite] .env.local changed, restarting server...
2024-11-16 00:29:54 11:29:54 PM [vite] server restarted.
```

I tried to get Ollama to run for many days, before it runs relatively stable now. There were a lot of small reasons, why it didn't work. 

But I have found a main cause of instability that very few people take into account:

Unfortunately I had to realize that all the small models like `Qwenb2.5-7B` have problems following the given prompt properly. As a result, the model does not follow the prescribed steps to deploy the applications. The plain source code is then displayed correctly in the chat, but isn't applied properly to the file workbench. Also, the commands for starting the internal web server are not always correct or in the right order, so that the preview often does not work (new bolt-terminal helps a lot!).

In my experience, this is not a technical problem with Ottodev, but is due to a lack of **prompt adherence** of the model.
I was previously only able to run the smaller models with my 4070 and was really annoyed by the instability. But since I have installed my 4090/24G in my server and now use `Qwen2.5-32B-instruct-Q4_K_M` with 12000 token context size:
- the files are created correctly every time
- the preview works almost every time

So to all those who are annoyed about instabilities in the project: Always consider that your chosen model maybe simply doesn't do what it is supposed to do according to the prompt. The PR to adapt the prompt at some point could be a game changer for customize different models and maybe the smaller one are working better then, too.

BTW: I wish I could raise the context size, but that would be only possible with (slow!) CPU offloading. As long as the context size is sufficient for me, I prefer full 100% GPU and the decision for the speed. Maybe this software (ottodev) and the model (Qwen2.5-32B) could actually be a reason to buy a 5090 with 32GB VRAM. I thought for a long time whether this 8GB of VRAM against the 4090 is worth it, but in this particular setup it would be exactly the difference to run a larger context window...

Important: Many thanks to @coleam00  for this excellent fork! I don't think you expected this success yourself and the project is now a lot more work for you than you thought ;) But I can see that the community is already contributing a lot and continues to grow.

I am already very grateful to you, because (for me) ottodev is the first only locally _working_ and functioning AI tool for the creation of full stack apps (at least prototypes)...

**Comment by coleam00** [comment]
@smarthiesbs I appreciate all your thoughts here and I totally agree that most issues with oTToDev just come down to the LLM hallucinating in some way, especially with the smaller ones.

Thanks for the kind words and yeah this project has blown up way more than I've expected haha. But it's incredible even though it's making me crazy busy!

**Comment by dustinwloring1988** [comment]
this is an outdated version please try the latest and start a new issue if the problem persists
