### ISSUE TITLE
Git Push doesn't seem to work?

### ISSUE THREAD

**Issue by nigelp** [coleam00/bolt.new-any-llm#349]
### Describe the bug

After entering all the required information, and clicking the Git Push button. Nothing happens.

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

1. click on GitPush button
2. enter in name, git pat, userid, repository name, etc
3. click on the execute button
4. nothing happens

### Expected behavior

I would expect the app to push the project to Github.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
windows 10
chrome canary

**Comment by kustomzone** [comment]
Works here in fine grained or classic.
Double check you have `Read and Write access to code` which in turn adds ` Read access to metadata` as mandatory.

GH permissions are no well laid out so we'll need to add simple dialogs rather than following dev console closely.

**Comment by Freffles** [comment]
been running on windows in docker container. did not work for me either.

**Comment by kustomzone** [comment]
It's hard to find by design i'm sure. I think "content" was the winner.

I'm just adding git pull to my own project which i'm making an app for as PRs are beyond me with all the Docker and third-party API stuff being added here.  My goal is to remove those and concentrate on simple push/pull from Github to HuggingFace and likely a P2P option as well to make human/agent code sharing easier. Also cos all my eggs are in M$'s basket atm which is the real issue. I find Github's increasing complexity is aimed at large enterprises with staff to figure out all the mess they make. Tried to remove 1 action from a fork yesterday and it seemed very well hidden (as i said) by design.

**Comment by seoninja13** [comment]
> Double check you have `Read and Write access to code` which in turn adds ` Read access to metadata` as mandatory.

Where exactly are these ? I dont see at in "Settings
"

**Comment by Freffles** [comment]
> > Double check you have `Read and Write access to code` which in turn adds ` Read access to metadata` as mandatory.
> 
> Where exactly are these ? I dont see at in "Settings "

its a process. Once you have selected settings, look over to the left sidebar all the way at the bottom to find developer settings.

**Comment by nigelp** [comment]
Hmm..don't seem to have developer settings here @Freffles

**Comment by kustomzone** [comment]
The layout for an Org is different than User profile. Have to set up token access from User (Admin) for your Org access tokens.
Fine grained let's us select a repo from the org then you can specify the permissions. At first we aren't able to add repos from the org until adding it on the user admin side.

**Comment by nigelp** [comment]
Thanks very much @kustomzone. So I have to go through all this if I want to push a Bolt/oTToDev project to Github?

**Comment by kustomzone** [comment]
Unfortunately yes. Haven't checked doing it from console or Github Desktop or elsewhere. I'm just using GH's interface and push/pulling from Bolt.

**Comment by Freffles** [comment]
> Thanks I think I get it now. We need to create a token with full Read and Write access to code permissions for each Bolt project repository individually? Then we can push?

No, the permissions apply to the token. Anything you create with that token in play will work.

**Comment by nigelp** [comment]
@Freffles oh. Sorry to be dense. So if I create one token which I use with a Bolt project, then every project is OK? Or do I have to input the token somewhere each time? I'm not really too familiar with this stuff as you can tell, so thanks for your help.

**Comment by Freffles** [comment]
@nigelp you were too quick 😂. I deleted that comment when I re-read the comments by @kustomzone. What I said about one token was true for me but if you're on a fine grained token then I would defer to @kustomzone who indicated how that works.

**Comment by nigelp** [comment]
Ouch, my brain....  😂

**Comment by dustinwloring1988** [comment]
please try again this is working good

**Comment by Freffles** [comment]
When I did mind I set ALL permissions to the max because I didn't know which ones needed to be set. I'm not concerned about that because the permissions only apply to my account and not to any repo (AFAIK). So, maybe you're permissions are correct since you did get the readme. Maybe double check them. Then you could ask bolt to create a gitignore for your project. Without the gitignore it's probably trying to push a metric sh1t ton of files. 

Then give it another try. Another way, maybe less painful, is to sync your project to a local folder and then use VS Code or Git Desktop etc. to create a local repo and then push that to Git. But don't forget the gitignore.

**Comment by nigelp** [comment]
SUCCESS!! Thanks for your patience. Apparently I didn't give it enough permissions or something. I did what you said @Freffles and it went up super slickly. Thanks very much. I still do think a short guide on how to do it (e.g. what permissions exactly do we need?) would help.  The gitignore was also a great suggestion. Thanks. :)
