### ISSUE TITLE
No code generated for ollama

### ISSUE THREAD

**Issue by raghusbhat** [coleam00/bolt.new-any-llm#87]
### Describe the bug

No code file(s) generated in the editor when using local Ollama models.
Running on Windows 11.

_**Note that Ollama models are being correctly recognized and working correctly.**_
---
![Frame 2](https://github.com/user-attachments/assets/e1e819ff-d5db-4304-a2e1-b76c7494f037)

### Link to the Bolt URL that caused the error

https://github.com/coleam00/bolt.new-any-llm

### Steps to reproduce

1. pnpm run dev
2. Open http://localhost:5173/ in chrome canary _[ Version 132.0.6798.1 (Official Build) canary-dcheck (64-bit) ]_
3. Enter prompt 

### Screen Recording / Screenshot

![Frame 2](https://github.com/user-attachments/assets/ad7e34e9-a895-4abc-ac9d-3c441ca205da)

---
![image](https://github.com/user-attachments/assets/4ab821d7-2ead-41fe-bad6-5a85462af8ed)
---
![image](https://github.com/user-attachments/assets/96cd78c7-d805-4e82-9312-97991d39d213)
---
![Frame 3](https://github.com/user-attachments/assets/3d4b8ad2-bc7c-47f4-8d00-ebf706454b34)

### Platform

- OS: Windows 11 10.0.26100 Build 26100
- Browser: Chrome Canary
- Version: 132.0.6798.1 (Official Build) canary-dcheck (64-bit)

### Additional context

There are no errors in console for ```pnpm run dev```
What am I doing wrong?

**Comment by TIPYexe** [comment]
I'm facing the same issue

**Comment by finngreig** [comment]
Same issue here as well

**Comment by zaazo** [comment]
Same

**Comment by shubhamkashyapdev** [comment]
Trying to use deepseek with ollama but its always giving anthropic key error in terminal

**Comment by karlbibby** [comment]
Same issue

**Comment by Starlord27** [comment]
same issue

**Comment by Starlord27** [comment]
I found  { name: 'llama-3.1-70b-versatile', label: 'Llama 3.1 70b (Groq)', provider: 'Groq' },
  { name: 'llama-3.1-8b-instant', label: 'Llama 3.1 8b (Groq)', provider: 'Groq' },
  { name: 'llama-3.2-11b-vision-preview', label: 'Llama 3.2 11b (Groq)', provider: 'Groq' },
  { name: 'llama-3.2-3b-preview', label: 'Llama 3.2 3b (Groq)', provider: 'Groq' },
  { name: 'llama-3.2-1b-preview', label: 'Llama 3.2 1b (Groq)', provider: 'Groq' },
  
  in /utils/constants.ts
  
  and run command ollama run llama3.1:8b

**Comment by MisterTricky** [comment]
Hi @raghusbhat, have you tried teliing it to specifically execute instructions in the Webcontainer ?
Its not ideal, and it doesnt always work. Especially with the smaller models, if you go below 7B you can almost forget about it using the webcontainer to create the files/projects at all, but that is only in my experience. Its also probably related to the reasoning capabilities of the LLM, and the context window of the LLM in question since the actual prompt seems quite large. 

![Bolt-webcontainer-issues-ollama](https://github.com/user-attachments/assets/ccdffbee-9351-47de-a64e-483e226e7755)

There are others here who know much more than myself about this, so maybe I am completely wrong

**Comment by raghusbhat** [comment]
Closing this duplicate thread as there's already ongoing thread with the same issue.

https://github.com/coleam00/bolt.new-any-llm/issues/63

Thanks @MisterTricky.
